//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webpro_quiz2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class @event
    {
        public int event_id { get; set; }
        public int event_organizer { get; set; }
        public string event_name { get; set; }
        public decimal event_price { get; set; }
        public string event_place { get; set; }
        public System.DateTime event_start_date { get; set; }
        public System.TimeSpan event_start_time { get; set; }
        public System.DateTime event_end_date { get; set; }
        public System.TimeSpan event_end_time { get; set; }
    
        public virtual user user { get; set; }
    }
}
